# Generated by Django 3.1 on 2020-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DubboControllerLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128, verbose_name='服务名')),
                ('dubbo_method', models.CharField(max_length=64, verbose_name='方法名')),
                ('params_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='参数类型')),
                ('params', models.CharField(default='', max_length=2048, verbose_name='参数')),
                ('user_id', models.IntegerField(verbose_name='请求人的ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Dubbo接口请求记录',
                'verbose_name_plural': 'Dubbo接口请求记录',
                'db_table': 'dubbo_controller_logs',
            },
        ),
    ]
